pipeline {

    agent any

    checkoutToSubdirectory('spring-petclinic')

    stages {
        stage('Prepare') {
            steps {
                sh "./mvnw clean install"
            }
        }
    }
}