node {
  def commit_id
  stage('Preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"
    commit_id = readFile('.git/commit-id').trim()
  }
  dir('expressjs-starter') {
    stage('Installing dependencies') {
      nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'npm install'
      }
    }
    stage('Testing') {
      nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'npm test'
      }
    }
    stage('Notify') {
      sh "echo Pipeline is finished"
    }
  }
}